### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by liulsg** [AIFSH/ComfyUI-MimicBrush#1]
!!! Exception during processing!!! Error(s) in loading state_dict for CLIPVisionModelWithProjection:
        Unexpected key(s) in state_dict: "vision_model.embeddings.position_ids".
Traceback (most recent call last):
  File "G:\AI\ComfyUI_M\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\AI\ComfyUI_M\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\AI\ComfyUI_M\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\AI\ComfyUI_M\ComfyUI\custom_nodes\ComfyUI-MimicBrush\__init__.py", line 91, in generate
    synthesis, depth_pred = inference_single_image(ref_image.copy(), image.copy(), mask.copy(),
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\AI\ComfyUI_M\ComfyUI\custom_nodes\ComfyUI-MimicBrush\infer.py", line 221, in inference_single_image
    pred, depth_pred = infer_single(ref_image, tar_image, tar_mask, seed, num_inference_steps=ddim_steps, guidance_scale = scale, enable_shape_control = enable_shape_control)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\AI\ComfyUI_M\ComfyUI\custom_nodes\ComfyUI-MimicBrush\infer.py", line 164, in infer_single
    mimicbrush_model = MimicBrush_RefNet(pipe, image_encoder_path, mimicbrush_ckpt,  depth_anything_model, depth_guider, referencenet, device)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\AI\ComfyUI_M\ComfyUI\custom_nodes\ComfyUI-MimicBrush\MimicBrush\mimicbrush\mimicbrush_referencenet.py", line 42, in __init__
    self.load_checkpoint()
  File "G:\AI\ComfyUI_M\ComfyUI\custom_nodes\ComfyUI-MimicBrush\MimicBrush\mimicbrush\mimicbrush_referencenet.py", line 58, in load_checkpoint
    self.image_encoder.load_state_dict(state_dict["image_encoder"])
  File "G:\AI\ComfyUI_M\python_miniconda\Lib\site-packages\torch\nn\modules\module.py", line 2153, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for CLIPVisionModelWithProjection:
        Unexpected key(s) in state_dict: "vision_model.embeddings.position_ids".

Prompt executed in 48.80 seconds

**Comment by AIFSH** [comment]
'''
pip install transformers==4.25.1
'''

**Comment by SongOnWater** [comment]
> ''' pip install transformers==4.25.1 '''

I had tested on this configuration, and also got the same error. I run on a RTX-3090 with Ubuntu 22.04.2 LTS.

**Comment by liulsg** [comment]
@AIFSH 
The comfyui chatts plugin requires transformers~=4.41.1
What is required for the price difference of ComfyUI MinimcBrush is transformers==4.25.1
At least align the versions with your own plugins
